name: Publish bioTEA on PyPi

on:
  release:
    types: [published]

jobs:
  rebuild-docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Update release string
        run: echo "${{ github.event.release.tag_name }}" > ./VERSION
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./src
          push: true
          tags: |
            cmalabscience/biotea-box:${{ github.event.release.tag_name }}

  publish-pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10
    - name: Install pypa/build
      working-directory: ./src/bioTea
      run: >-
        python -m
        pip install
        -r requirements-dev.txt
        --user
    - name: Build a binary wheel and a source tarball
      working-directory: ./src/bioTea
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
